FROM apache/airflow:2.6.3-python3.10

ARG AIRFLOW_USER_HOME=/opt/airflow
ENV PYTHONPATH=$PYTHONPATH:${AIRFLOW_USER_HOME}

# Python packages required for th Selenium Plugin
USER airflow

RUN pip install docker && \
    pip install selenium && \
    pip install bs4 && \
    pip install lxml

USER root

# # Install Docker inside the image
# RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
#     sh get-docker.sh

RUN groupadd --gid 1001 docker \
   && usermod -aG docker airflow 

USER airflow

RUN mkdir downloads
